/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.2.0 Wed Apr 28 12:27:33 2021.
 */

#include <string.h>

#include "test.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int test_panic_pack(
    uint8_t *dst_p,
    const struct test_panic_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->panic, 6u, 0xc0u);

    return (8);
}

int test_panic_unpack(
    struct test_panic_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->panic = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);

    return (0);
}

bool test_panic_panic_is_in_range(uint8_t value)
{
    return (value <= 0u);
}

int test_dashboard_pack(
    uint8_t *dst_p,
    const struct test_dashboard_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->error_code, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->ready2_drive, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->steering_pos, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->start_button, 0u, 0xffu);

    return (4);
}

int test_dashboard_unpack(
    struct test_dashboard_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->error_code = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ready2_drive = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->steering_pos = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->start_button = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

bool test_dashboard_error_code_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool test_dashboard_ready2_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool test_dashboard_steering_pos_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool test_dashboard_start_button_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
